import { Entity, Property, PrimaryKey } from "@mikro-orm/core";
import { Field, ID, ObjectType, InterfaceType } from "@nestjs/graphql";
import { generate } from "shortid";

@Entity()
@InterfaceType("Node")
class Node {
  @Field(() => ID, { description: "An random string generated by shortid package" })
  @PrimaryKey()
  public id: string = generate();
}

@Entity()
@ObjectType({ implements: [Node] })
export abstract class BaseModel extends Node {
  @Field()
  @Property()
  public createdAt: Date = new Date();

  @Field()
  @Property({ onUpdate: () => new Date() })
  public updatedAt: Date = new Date();
}
